---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

```{r}
data("rest_inspec")

rest_inspec =
  rest_inspec |>
  select(boro, critical_flag, cuisine_description, violation_code, violation_description, score, zipcode, grade, grade_date) |>
  group_by(boro) |>
  filter(boro == "MANHATTAN") |>
  mutate(boro = 
recode(boro, "MANHATTAN" = "Manhattan"),
critical_flag = factor(critical_flag, order = TRUE, levels = c("Not Applicable", "Not Critical", "Critical")),
cuisine_description = as.factor(cuisine_description)
) 

rest_inspec =
  rest_inspec |>
  filter(cuisine_description == c("Italian", "Korean", "American", "Japanese", "French", "African", "Chinese","Mexican"))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot

```{r}
rest_inspec |>
  mutate(text_label = str_c("Violation Code ", violation_code, "\nViolation Level ", critical_flag)) |>
  plot_ly(
    x = ~grade_date, y = ~score, type = "scatter", mode = "markers", color = ~cuisine_description ,text = ~text_label, alpha = 0.5)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot

```{r}
rest_inspec_box = 
  rest_inspec |>
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) |> 
  ggplot(aes(x = cuisine_description, y = score, fill = cuisine_description)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + labs(
    title = "Inspection Score Data per Restaurant Style",
    subtitle = "Manhattan Restaurants"
  )

ggplotly(rest_inspec_box)
```

### Barchart

```{r}
bar_ggplot = 
  rest_inspec |>
  count (cuisine_description) |>   
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) |>
  ggplot(aes(x = cuisine_description, y = n, fill = cuisine_description, color = cuisine_description)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + labs(
    title = "Number of Violations per Cuisine",
    subtitle = "Manhattan Restaurants"
  )

ggplotly(bar_ggplot)
```

